FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y curl

RUN curl -LO https://dl.k8s.io/release/v1.33.1/bin/linux/amd64/kubectl \
 && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

USER jenkins
